---
branches:
  # Ignore pull requests to the named branches
  ignore:
    - "wip"
    - "feedback"

review:
  fail_on_comments: false

linters:
  stylelint:
    fixer: true
  eslint:
    fixer: true
  checkstyle:
    config: ./checkstyle.xml

fixers:
  enable: true
